# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

  ## general prefs
  app_url: ello-bor.herokuapp.com
  parent_url: ello.co
  base_site_title: 'The Ello Bill of Rights'
  base_company_name: 'Ello'
  general_email_address: 'hello@ello.co'
  twitter_username: elloword
  ios_app_link: https://itunes.apple.com/app/apple-store/id953614327?pt=117139389&ct=billofrights&mt=8

  ## lockup password
  lockup_codeword:

  ## postmark stuff
  postmark_key: 

  # mailcatcher, set to true to turn on in dev mode
  mail_catcher: true

  ## smtp email stuff (or sendgrid)
  email_address: 'smtp.sendgrid.net'
  email_port: 587
  email_domain: <%= ENV["EMAIL_DOMAIN"] %>
  email_username: <%= ENV["EMAIL_USERNAME"] %>
  email_password: <%= ENV["EMAIL_PASSWORD"] %>

test:
  secret_key_base: 8ed5f48ae82a17ddd2480c9db2e9986c52748675be1ca41c94262af68378d0ac61eb04cc9045885cc63e96935e2b00608a3e4b052a05f73dbe35b98566fb3ed4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

  ## general prefs
  app_url: bill-of-rights.ello.co
  parent_url: ello.co
  base_site_title: 'The Ello Bill of Rights'
  base_company_name: 'Ello'
  general_email_address: 'hello@ello.co'
  twitter_username: elloword

  ## lockup password
  lockup_codeword:

  ## postmark stuff
  postmark_key: 

  # mailcatcher, set to true to turn on in dev mode
  mail_catcher:

  ## smtp email stuff (or sendgrid)
  email_address: 'smtp.sendgrid.net'
  email_port: 587
  email_domain: <%= ENV["EMAIL_DOMAIN"] %>
  email_username: <%= ENV["EMAIL_USERNAME"] %>
  email_password: <%= ENV["EMAIL_PASSWORD"] %>

